### ISSUE TITLE
personal config broken link?

### ISSUE THREAD

**Issue by shapr** [volhovM/orgstat#16]
I'd like to use orgstat for time reporting, but I'm stuck on the configuration.
I wanted to look at @volhovm 's personal config ( https://github.com/volhovm/dotfiles/blob/master/config/.orgstat.yaml )
but the repo is gone (or private).

Does anyone have a starter config file they would suggest?

**Comment by volhovm** [comment]
Oh, sorry. I've just uploaded this to the main repo. Does this work for you?

**Comment by shapr** [comment]
Yes, thank you!
